"""add_system_audit_log_table

Revision ID: ed29b7bff4b1
Revises: d7c1a2b3c4d5
Create Date: 2026-02-03 10:28:06.551619

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed29b7bff4b1"
down_revision: Union[str, None] = "d7c1a2b3c4d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This migration was autogenerated and may already be applied on some dev DBs.
    # Be defensive to avoid duplicate-table/duplicate-column failures.
    bind = op.get_bind()
    existing_tables = set(sa.inspect(bind).get_table_names())
    if "system_audit_log" in existing_tables and "system_settings" in existing_tables:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("setting_key", sa.String(), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("details", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_system_audit_log_created_at",
        "system_audit_log",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_audit_log_deleted_at"),
        "system_audit_log",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_audit_log_id"), "system_audit_log", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_system_audit_log_user_id"),
        "system_audit_log",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key", name="uq_user_setting_key"),
    )
    op.create_index(
        op.f("ix_system_settings_deleted_at"),
        "system_settings",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_settings_id"), "system_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_system_settings_key"), "system_settings", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_system_settings_user_id"), "system_settings", ["user_id"], unique=False
    )
    op.create_index(
        "ix_system_settings_user_id_key",
        "system_settings",
        ["user_id", "key"],
        unique=False,
    )

    # Adding SoftDeleteMixin fields if they were missing (based on autogen)
    op.add_column(
        "file_delivery_log",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_file_delivery_log_deleted_at"),
        "file_delivery_log",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "patient_files",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_patient_files_deleted_at"),
        "patient_files",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "telegram_link_tokens",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_telegram_link_tokens_deleted_at"),
        "telegram_link_tokens",
        ["deleted_at"],
        unique=False,
    )

    # Some index cleanups that seem intentional
    op.drop_index(op.f("ix_patients_birth_date"), table_name="patients")
    op.drop_index(op.f("ix_transactions_patient_id"), table_name="transactions")

    # Check constraints on telegram_link_tokens
    op.drop_constraint(
        "telegram_link_tokens_code_key", "telegram_link_tokens", type_="unique"
    )
    op.drop_index(
        op.f("ix_telegram_link_tokens_code"), table_name="telegram_link_tokens"
    )
    op.create_index(
        op.f("ix_telegram_link_tokens_code"),
        "telegram_link_tokens",
        ["code"],
        unique=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram_link_tokens_code"), table_name="telegram_link_tokens"
    )
    op.create_index(
        op.f("ix_telegram_link_tokens_code"),
        "telegram_link_tokens",
        ["code"],
        unique=False,
    )
    op.create_unique_constraint(
        "telegram_link_tokens_code_key",
        "telegram_link_tokens",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_telegram_link_tokens_deleted_at"), table_name="telegram_link_tokens"
    )
    op.drop_column("telegram_link_tokens", "deleted_at")

    op.create_index(
        op.f("ix_transactions_patient_id"), "transactions", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_patients_birth_date"), "patients", ["birth_date"], unique=False
    )

    op.drop_index(op.f("ix_patient_files_deleted_at"), table_name="patient_files")
    op.drop_column("patient_files", "deleted_at")
    op.drop_index(
        op.f("ix_file_delivery_log_deleted_at"), table_name="file_delivery_log"
    )
    op.drop_column("file_delivery_log", "deleted_at")

    op.drop_index("ix_system_settings_user_id_key", table_name="system_settings")
    op.drop_index(op.f("ix_system_settings_user_id"), table_name="system_settings")
    op.drop_index(op.f("ix_system_settings_key"), table_name="system_settings")
    op.drop_index(op.f("ix_system_settings_id"), table_name="system_settings")
    op.drop_index(op.f("ix_system_settings_deleted_at"), table_name="system_settings")
    op.drop_table("system_settings")

    op.drop_index(op.f("ix_system_audit_log_user_id"), table_name="system_audit_log")
    op.drop_index(op.f("ix_system_audit_log_id"), table_name="system_audit_log")
    op.drop_index(op.f("ix_system_audit_log_deleted_at"), table_name="system_audit_log")
    op.drop_index("ix_system_audit_log_created_at", table_name="system_audit_log")
    op.drop_table("system_audit_log")
    # ### end Alembic commands ###
