"""add_system_audit_log_table

Revision ID: ed29b7bff4b1
Revises: d7c1a2b3c4d5
Create Date: 2026-02-03 10:28:06.551619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed29b7bff4b1'
down_revision: Union[str, None] = 'd7c1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_audit_log_created_at', 'system_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_audit_log_deleted_at'), 'system_audit_log', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_system_audit_log_id'), 'system_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_system_audit_log_user_id'), 'system_audit_log', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_setting_key')
    )
    op.create_index(op.f('ix_system_settings_deleted_at'), 'system_settings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_index(op.f('ix_system_settings_user_id'), 'system_settings', ['user_id'], unique=False)
    op.create_index('ix_system_settings_user_id_key', 'system_settings', ['user_id', 'key'], unique=False)
    op.drop_index(op.f('ix_queue_items_deleted_at'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_id'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_queue_date'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_status'), table_name='queue_items')
    op.drop_table('queue_items')
    op.drop_index(op.f('ix_appointments_deleted_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.add_column('file_delivery_log', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_file_delivery_log_deleted_at'), 'file_delivery_log', ['deleted_at'], unique=False)
    op.add_column('patient_files', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_patient_files_deleted_at'), 'patient_files', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_patients_birth_date'), table_name='patients')
    op.add_column('telegram_link_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('telegram_link_tokens_code_key'), 'telegram_link_tokens', type_='unique')
    op.drop_index(op.f('ix_telegram_link_tokens_code'), table_name='telegram_link_tokens')
    op.create_index(op.f('ix_telegram_link_tokens_code'), 'telegram_link_tokens', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_link_tokens_deleted_at'), 'telegram_link_tokens', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_transactions_patient_id'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_patient_id'), 'transactions', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_telegram_link_tokens_deleted_at'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_code'), table_name='telegram_link_tokens')
    op.create_index(op.f('ix_telegram_link_tokens_code'), 'telegram_link_tokens', ['code'], unique=False)
    op.create_unique_constraint(op.f('telegram_link_tokens_code_key'), 'telegram_link_tokens', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('telegram_link_tokens', 'deleted_at')
    op.create_index(op.f('ix_patients_birth_date'), 'patients', ['birth_date'], unique=False)
    op.drop_index(op.f('ix_patient_files_deleted_at'), table_name='patient_files')
    op.drop_column('patient_files', 'deleted_at')
    op.drop_index(op.f('ix_file_delivery_log_deleted_at'), table_name='file_delivery_log')
    op.drop_column('file_delivery_log', 'deleted_at')
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('appointments_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_deleted_at'), 'appointments', ['deleted_at'], unique=False)
    op.create_table('queue_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('queue_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('queue_items_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('queue_items_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('queue_items_pkey')),
    sa.UniqueConstraint('doctor_id', 'queue_date', 'sequence', name=op.f('uq_queue_doctor_date_seq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_queue_items_status'), 'queue_items', ['status'], unique=False)
    op.create_index(op.f('ix_queue_items_queue_date'), 'queue_items', ['queue_date'], unique=False)
    op.create_index(op.f('ix_queue_items_id'), 'queue_items', ['id'], unique=False)
    op.create_index(op.f('ix_queue_items_deleted_at'), 'queue_items', ['deleted_at'], unique=False)
    op.drop_index('ix_system_settings_user_id_key', table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_user_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_deleted_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_audit_log_user_id'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_id'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_deleted_at'), table_name='system_audit_log')
    op.drop_index('ix_system_audit_log_created_at', table_name='system_audit_log')
    op.drop_table('system_audit_log')
    # ### end Alembic commands ###
