from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, field_validator


class QueueItemBase(BaseModel):
    patient_name: str
    patient_id: Optional[int] = None
    doctor_id: Optional[int] = None
    status: str = "WAITING"


class QueueItemCreate(BaseModel):
    """Create schema - ticket_number is generated by backend"""

    patient_name: str
    patient_id: int
    doctor_id: int  # Required for queue prefix generation
    status: str = "WAITING"

    @field_validator("patient_name")
    @classmethod
    def validate_patient_name(cls, v: str) -> str:
        if not (v or "").strip():
            raise ValueError("patient_name must not be empty")
        return v.strip()


class QueueItemUpdate(BaseModel):
    status: str


class QueueItemRead(QueueItemBase):
    id: int
    ticket_number: str  # e.g., "A-001", "B-042"
    created_at: datetime
    doctor_name: Optional[str] = None  # Calculated field for convenience

    model_config = ConfigDict(from_attributes=True)
